package com.qamindslab.moduleone.java.exercise.SeleniumTest;
import org.openqa.selenium.chrome.ChromeDriver;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoogleSearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void googleSearch2() {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(1661, 933));
        System.out.println("Current URL is:" + driver.getCurrentUrl());

        driver.navigate().to("https://www.facebook.com/");
        System.out.println("Current URL is:" + driver.getCurrentUrl());

        driver.navigate().to("https://www.espn.com/");
        System.out.println("Current URL is:" + driver.getCurrentUrl());

        driver.navigate().back();
        driver.navigate().back();
        System.out.println("Current URL is:" + driver.getCurrentUrl());

        driver.navigate().forward();
        System.out.println("Current URL is:" + driver.getCurrentUrl());

        assert (driver.getCurrentUrl().equals("https://www.facebook.com/")) : "No nos encontramos en facebook: " + driver.getCurrentUrl() ;

        driver.navigate().refresh();
        driver.close();
    }
}