package com.qamindslab.moduleone.java.exercise.SeleniumTest;
import org.openqa.selenium.chrome.ChromeDriver;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoogleSearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void googleSearch2() {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(1661, 933));
        System.out.println("Titulo:" + driver.getTitle());
        System.out.println("Source code: " + driver.getPageSource());

        /*driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("metallica");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        {
            WebElement element = driver.findElement(By.linkText("metallica.com"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector("div:nth-child(3) > .tF2Cxc .LC20lb")).click();
        driver.findElement(By.cssSelector(".svg-menu-white-dims")).click();
        driver.findElement(By.linkText("Upcoming Dates")).click();
        driver.findElement(By.cssSelector(".show:nth-child(1) .venue-name > .venue-name")).click();*/
    }
}