/*package com.qamindslab.moduleone.selenium.example.seleniumide;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class TheMatrixPageTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "src/main/resources/geckodriver");

        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void theMatrixPageTest() {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(1088, 660));
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("Matrix");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector("div:nth-child(1) > .g > div > .g .LC20lb")).click();
        driver.findElement(By.cssSelector("p:nth-child(7)")).click();
        assertThat(driver.findElement(By.cssSelector("p:nth-child(7)")).getText(), is("The Matrix is a 1999 science fiction action film[5][6] written and directed by the Wachowskis.[a] It is the first installment in The Matrix film series. Starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano. It depicts a dystopian future in which humanity is unknowingly trapped inside a simulated reality, the Matrix, which intelligent machines have created to distract humans while using their bodies as an energy source.[7] When computer programmer Thomas Anderson, under the hacker alias \\\"Neo\\\", uncovers the truth, he \\\"is drawn into a rebellion against the machines\\\"[7] along with other people who have been freed from the Matrix."));
    }
}*/