package com.seleniumIDE;
// Generated by Selenium IDE
import org.junit.Test;
        import org.junit.Before;
        import org.junit.After;
        import static org.junit.Assert.*;
        import static org.hamcrest.CoreMatchers.is;
        import static org.hamcrest.core.IsNot.not;
        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.firefox.FirefoxDriver;
        import org.openqa.selenium.chrome.ChromeDriver;
        import org.openqa.selenium.remote.RemoteWebDriver;
        import org.openqa.selenium.remote.DesiredCapabilities;
        import org.openqa.selenium.Dimension;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.interactions.Actions;
        import org.openqa.selenium.support.ui.ExpectedConditions;
        import org.openqa.selenium.support.ui.WebDriverWait;
        import org.openqa.selenium.JavascriptExecutor;
        import org.openqa.selenium.Alert;
        import org.openqa.selenium.Keys;
        import java.util.*;
        import java.net.MalformedURLException;
        import java.net.URL;
public class pruebaSeleniumIDE {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {

        //Ubicacion chrome driver
        System.setProperty("webdriver.chrome.driver","src/main/resources/chromedriver.exe");

        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void prueba() {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(1288, 764));
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
        driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
        driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
        driver.findElement(By.name("q")).sendKeys(Keys.UP);
        driver.findElement(By.name("q")).sendKeys(Keys.UP);
        driver.findElement(By.name("q")).sendKeys("muy linux");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        js.executeScript("window.scrollTo(0,376)");
        js.executeScript("window.scrollTo(0,964)");
        driver.findElement(By.cssSelector(".css-47sehv")).click();
        js.executeScript("window.scrollTo(0,1008)");
        driver.findElement(By.cssSelector("#entry-43356 p:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("#entry-43356 p:nth-child(1)")).getText(), is("Ya está disponible Fedora 35, la última versión de la distribución comunitaria patrocinada por Red Hat que es además la gran pionera del avance tecnológico de Linux. En esta ocasión nos encontramos con un lanzamiento aparentemente menos rompedor que el[…]"));
    }
}